version: '3'

services:
  ros:
    build: .
    user: guest
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/video0:/dev/video0:mwr
    volumes:
      - .:/home/guest
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    entrypoint: /bin/bash -c "source /catkin_ws/devel/setup.bash && roslaunch rosbridge_server rosbridge_websocket.launch"
    ports:
      - "9090:9090"
