version: '3.1'

services:
  web:
    build: .
    container_name: rosbridge_web
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
    depends_on:
      - ros
    command: sleep infinity
  ros:
    build: ..
    container_name: rosbridge_server
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/video0:/dev/video0:mwr
    volumes:
      - ../dummy_sensor:/catkin_ws/src/dummy_sensor
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "9090:9090"
